/*
 * NotesExampleAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class NotesRequest 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5642111474853634988L;
    private String title;
    private int dueInDays;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("title")
    public String getTitle ( ) { 
        return this.title;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("title")
    public void setTitle (String value) { 
        this.title = value;
        notifyObservers(this.title);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("dueInDays")
    public int getDueInDays ( ) { 
        return this.dueInDays;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("dueInDays")
    public void setDueInDays (int value) { 
        this.dueInDays = value;
        notifyObservers(this.dueInDays);
    }
 
}
 