/*
 * NotesExampleAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum XTrackingExampleEnum {
    ACCOUNTING, //TODO: Write general description for this element
    PAYROLL, //TODO: Write general description for this element
    FINANCE; //TODO: Write general description for this element

    private static TreeMap<String, XTrackingExampleEnum> valueMap = new TreeMap<String, XTrackingExampleEnum>();
    private String value;

    static {
        ACCOUNTING.value = "accounting";
        PAYROLL.value = "payroll";
        FINANCE.value = "finance";

        valueMap.put("accounting", ACCOUNTING);
        valueMap.put("payroll", PAYROLL);
        valueMap.put("finance", FINANCE);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static XTrackingExampleEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of XTrackingExampleEnum values to list of string values
     * @param toConvert The list of XTrackingExampleEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<XTrackingExampleEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (XTrackingExampleEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 